---
application:
  name: "node-scraper"
  project: "node-scraper"
  organization: "QoveryCommunity"
  port: 8080
routers:
- name: "main-node-scraper"
  routes:
  - application_name: "node-scraper"
    paths:
    - "/*"
